export let items = [
    {
        "name" : "Henrik Jespersen| Rund stol",
        "image" : "../images/productimg/henrikjespersenstol.png",
        "price" : 11500,
        "save" : "../images/productimg/nofill.png",
        "putinbag": "../images/productimg/bag.png",
        "year":2023,
        "color":"dark",
        "id": 1,
        "model": "Mørk Egetræs stolm",
        "højde": "60cm",
        "bredde": "50cm",
        "stel": "Mørk egetræ",
        "farve": "Mørkebrunt med rødt skær",
        "designer": "Henrik Jespersen"
    }, 
    {
        "name" : "HjemmetsHerte|Giv navn",
        "price" : 800,
        "image" : "../images/productimg/morkegetrea.png",
        "save" : "../images/productimg/nofill.png",
        "putinbag": "../images/productimg/bag.png",
        "year":2023,
       "color":"dark",
       "id": 2,
       "model": "Mørk Egetræs stol",
       "højde": "60cm",
       "bredde": "50cm",
       "stel": "Mørk egetræ",
       "farve": "Mørkebrunt med rødt skær",
       "designer": "Hjemmets Hjerte"
    },
    {
        "name" : "Hjemmets Hjerte|Massiv stol|",
        "image": "../images/productimg/massive1.png",
        "price" : 4800,
        "putinbag": "../images/productimg/bag.png",
        "save" : "../images/productimg/nofill.png",
        "year":2020,
        "color":"light",
        "id": 3,
        "model": "Mørk Egetræs stol",
        "højde": "60cm",
        "bredde": "50cm",
        "stel": "Mørk egetræ",
        "farve": "Mørkebrunt med rødt skær",
        "designer": "Henrik Jespersen"
    },
    {
        "name" : "Hjemmets Hjerte|Massiv mørk egetræ",
        "price" : 1500,
        "image" : "../images/productimg/massive2.png",
        "save" : "../images/productimg/nofill.png",
        "putinbag" : "../images/productimg/bag.png",
        "year":2020,
        "color":"light",
        "id": 4,
        "model": "Mørk Egetræs stol",
        "højde": "60cm",
        "bredde": "50cm",
        "stel": "Mørk egetræ",
        "farve": "Mørkebrunt med rødt skær",
        "designer": "Hjemmets Hjerte"
    },
    {
        "name" : "Hjemmets Hjerte|lys tynd egetræ",
        "price" : 2500,
        "image" : "../images/productimg/lightlightchair.png",
        "save": "../images/productimg/nofill.png",
        "putinbag": "../images/productimg/bag.png",
        "year": 2008,
        "color":"light",
        "id": 5,
        "model": "Mørk Egetræs stol",
        "højde": "60cm",
        "bredde": "50cm",
        "stel": "Mørk egetræ",
        "farve": "Mørkebrunt med rødt skær",
        "designer": "Hjemmets Hjerte"

    },
    {
    "name": "Hjemmets Hjerte|Idunstol",
    "price": 2900,
    "image": "../images/productimg/idunstol.png",
    "save": "../images/productimg/nofill.png",
    "putinbag": "../images/productimg/bag.png",
    "year":2008,
    "color":"light",
    "id": 6,
    "model": "Mørk Egetræs stol",
    "højde": "60cm",
    "bredde": "50cm",
    "stel": "Mørk egetræ",
    "farve": "Mørkebrunt med rødt skær",
    "designer": "Henrik Jespersen"

    },
    {
        "name" : "Hjemmets Hjerte|Red-Oak-Chair",
        "image" : "../images/productimg/redoakchair.png",
        "price" : 6500,
        "save" : "../images/productimg/nofill.png",
        "putinbag": "../images/productimg/bag.png",
        "year":2008,
        "color":"dark",
        "id": 7,
        "model": "Mørk Egetræs stol",
        "højde": "60cm",
        "bredde": "50cm",
        "stel": "Mørk egetræ",
        "farve": "Mørkebrunt med rødt skær",
        "designer": "Hjemmets Hjerte"

    },
];
